"""Migrations for books package

Revision ID: 2869d1723c89
Revises: 31df6bc85038
Create Date: 2025-03-19 17:44:41.985272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2869d1723c89'
down_revision: Union[str, None] = '31df6bc85038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_categories',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_categories'))
    )
    op.create_index(op.f('ix_book_categories_name'), 'book_categories', ['name'], unique=True)
    op.create_table('book_titles',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('isbn', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['book_categories.id'], name=op.f('fk_book_titles_category_id_book_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_titles'))
    )
    op.create_index(op.f('ix_book_titles_author'), 'book_titles', ['author'], unique=False)
    op.create_index(op.f('ix_book_titles_isbn'), 'book_titles', ['isbn'], unique=True)
    op.create_index(op.f('ix_book_titles_title'), 'book_titles', ['title'], unique=False)
    op.create_table('books',
    sa.Column('title_id', sa.UUID(), nullable=False),
    sa.Column('book_title_id', sa.UUID(), nullable=False),
    sa.Column('edition', sa.String(), nullable=False),
    sa.Column('published_year', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BORROWED', 'LOST', name='bookstatus'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_title_id'], ['book_titles.id'], name=op.f('fk_books_book_title_id_book_titles')),
    sa.ForeignKeyConstraint(['title_id'], ['book_titles.id'], name=op.f('fk_books_title_id_book_titles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    op.create_index(op.f('ix_books_barcode'), 'books', ['barcode'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_barcode'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_book_titles_title'), table_name='book_titles')
    op.drop_index(op.f('ix_book_titles_isbn'), table_name='book_titles')
    op.drop_index(op.f('ix_book_titles_author'), table_name='book_titles')
    op.drop_table('book_titles')
    op.drop_index(op.f('ix_book_categories_name'), table_name='book_categories')
    op.drop_table('book_categories')
    # ### end Alembic commands ###
